Merged PR 561: Fix for dirty .gitmodules file
Error:
```
File "C:\Python3\lib\site-packages\MuEnvironment\CommonBuildEntry.py", line 295, in build_process
    VersionAggregator.GetVersionAggregator().ReportVersion(submodule_path, submodule.head.commit, VersionAggregator.VersionTypes.COMMIT)
AttributeError: 'NoneType' object has no attribute 'commit'
```
Solution:
Check submodule.head for type None before reporting it

Also: we were assuming that the submodule name was the submodule path and that they could be used as such. This update fixes that by removing `--name-only` from the `_get_submodule_list` function and retrieving the path instead.